### PR TITLE
Add Boiler Plate for the app

### LINKED ISSUE #17: Need to Create a Basic Barebone Structure for the Pod to get started.
Need to Create a Basic Barebone Structure for the Pod to get started. As per the design on figma.

### PR DESCRIPTION
**Pull request by nawed2611**
Fixes #17 

- Created `Components` and `Containers` for different sections of the app
- Added Documentation for the app

    └───src
    ├───App.js
    ├───index.js
    ├───assets
    │   └───images
            └───mlh-prep.png
    ├───components
    │   ├───MainNavbar
    │   ├───SecNavbar
    ├───containers
    │   ├───Footer
    │   ├───Header
    │   ├───Hotels
    │   ├───Main
    │   ├───RandomQuote
    │   └───WeatherAPI

### CODE REVIEW

**Comment by Buly1601** [comment]
quick quesiton before merging, was this the intended outcome of the pr? 
image

**Comment by nawed2611** [comment]
> quick quesiton before merging, was this the intended outcome of the pr? image

This is intended as we wanted to create a Boiler plate for the app


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by nawed2611** [comment]
But now other fellows have also worked on this PR

**Comment by deepanshug4** [comment]
This PR contains the fixes for issues:
[Issue #17](https://github.com/MLH-Fellowship/prep-project-22.AUG.PREP.1/issues/17) completed by @nawed2611 @XooTB.
[Issue #16](https://github.com/MLH-Fellowship/prep-project-22.AUG.PREP.1/issues/16) completed by @jyotsnad246 @Suven-p.
[Issue #3](https://github.com/MLH-Fellowship/prep-project-22.AUG.PREP.1/issues/3) completed by @gopivaibhav @vanichitkara.
[Issue #9](https://github.com/MLH-Fellowship/prep-project-22.AUG.PREP.1/issues/9) completed by @aakankshabhende @deepanshug4.
[Issue #10](https://github.com/MLH-Fellowship/prep-project-22.AUG.PREP.1/issues/10) completed by @nawed2611 @kartikmehta8.
[Issue #18](https://github.com/MLH-Fellowship/prep-project-22.AUG.PREP.1/issues/18) completed by @juhiechandra @hello-fri-end @XooTB.
[Issue #11](https://github.com/MLH-Fellowship/prep-project-22.AUG.PREP.1/issues/11) to some extent. Worked upon by @JooZef315 @chaytanyasinha.

**Pull request merged**
